### ISSUE TITLE
psiturk.user_utils.print_to_log doesn't exist

### ISSUE THREAD

**Issue by pfeyz** [NYUCCL/whoops_yall#1]
the import statement at
https://github.com/NYUCCL/whoops_yall/blob/master/custom.py#L10

and the calls to print_to_log that follow it cause the experiment to fail

But after removing them I sucessfully whoops-paid somebody, which was pretty cool!

I now see that print_to_log is on the psiturk dev branch.

**Comment by gureckis** [comment]
yeah, whoops ya'll.
