### ISSUE TITLE
Updating this repo to work with current code base?

### ISSUE THREAD

**Issue by c-j-bates** [NYUCCL/whoops_yall#10]
I'm trying to use this tool with the current psiturk master branch and python 3. However, I run into issues when I try to turn on the server. Specifically, I get gunicorn errors (gunicorn.errors.HaltServer: <HaltServer 'Worker failed to boot.' 3>). This seems to be happening in the custom.py code, because if I replace that file with the one from the current example stroop repo, then I can start the server no problem. Of course, then I can't actually use whoops y'all as intended. What changes would need to be made in order to update this code to work with the current psiturk head? Would it be easy? I was trying to comb through the code to see what might need updating, but I'm a little out of my depth.

**Comment by deargle** [comment]
Look at your server.log file for the error. You're probably missing a pip library.

**Comment by deargle** [comment]
Also, try the psiturk from pip, which supports python 3. Master branch has biiig changes.

**Comment by c-j-bates** [comment]
I'm getting:

ImportError: cannot import name 'Base' from 'psiturk.db'

I assume this function existed in an earlier version of db.py?

**Comment by deargle** [comment]
Yes, it exists in pip versions of psiturk. Closing, since master is no longer the "current code base" on psiturk (it's the dev branch). We can revisit when psiturk 3 is released.
